name: Build TrueControl APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Expo
      run: npm install -g @expo/cli eas-cli
      
    - name: Login to Expo (if token provided)
      if: env.EXPO_TOKEN != ''
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: eas login --non-interactive
      
    - name: Build APK with EAS
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        if [ -n "$EXPO_TOKEN" ]; then
          eas build --platform android --profile preview --non-interactive
        else
          echo "No EXPO_TOKEN found. Please set up an Expo account and token."
          echo "For now, we'll try a local build approach..."
          npx expo export
        fi
        
    - name: Download EAS build (if successful)
      if: env.EXPO_TOKEN != ''
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        # EAS build creates a downloadable link
        echo "Check your Expo dashboard for the built APK"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          .expo/
          *.log
