name: Build TrueControl Android APK

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: |
        npm install
        
    - name: Install Expo CLI
      run: |
        npm install -g @expo/cli eas-cli
        
    - name: Verify Expo installation
      run: |
        npx expo --version
        
    - name: Setup EAS (if using EAS build)
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        if [ ! -z "$EXPO_TOKEN" ]; then
          eas login --non-interactive
        fi
        
    - name: Build Android APK (Local Build)
      run: |
        # Try local build first
        npx expo run:android --variant release || echo "Local build failed, trying alternative"
        
    - name: Build Android APK (Alternative method)
      if: failure()
      run: |
        # Alternative build method
        npx expo build:android --type apk --non-interactive || npx expo export:embed
        
    - name: Find APK files
      run: |
        find . -name "*.apk" -type f
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: TrueControl-Android-APK
        path: |
          **/*.apk
          **/app-release.apk
          build/outputs/apk/**/*.apk
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
